var aNavData=[
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p1.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米9",
			price:"2999元",
			tag:"新品",
		},
		{
			url:"https://www.kuazhu.com/",
			src:"imgs/p2.jpg",
			name:"小米MS",
			price:"3999元",
			tag:"热销",
		}
	],
	[],
	[]
]